"""Native image classification helpers for VisionHub."""

from .native import (
    CLASSIFIER_AUGMENTATION_PRESET_NONE,
    CLASSIFIER_AUGMENTATION_PRESET_PHANTOM,
    CLASSIFIER_AUGMENTATION_PRESET_REFERENCE,
    CLASSIFIER_AUGMENTATION_PRESETS,
    LEAST_CONFUSED_SELECTION_METRIC,
    NATIVE_PYTORCH_CLASSIFIER_AVAILABLE,
    NativePyTorchClassifier,
    SUPPORTED_NATIVE_PYTORCH_CLASSIFIER_ARCHITECTURES,
    build_native_classifier_eval_transform,
    build_native_classifier_model,
    export_native_classifier_to_onnx,
    find_classifier_metadata_json,
    load_classifier_metadata_json,
    normalize_classifier_augmentation_preset,
    normalize_native_classifier_architecture,
    resolve_auto_classifier_optimizer,
    resolve_native_classifier_device,
    resolve_native_classifier_model_path,
    resolve_native_classifier_training_options,
    summarize_classifier_imagefolder_root,
    train_native_classifier,
)

__all__ = [
    "CLASSIFIER_AUGMENTATION_PRESET_NONE",
    "CLASSIFIER_AUGMENTATION_PRESET_PHANTOM",
    "CLASSIFIER_AUGMENTATION_PRESET_REFERENCE",
    "CLASSIFIER_AUGMENTATION_PRESETS",
    "LEAST_CONFUSED_SELECTION_METRIC",
    "NATIVE_PYTORCH_CLASSIFIER_AVAILABLE",
    "NativePyTorchClassifier",
    "SUPPORTED_NATIVE_PYTORCH_CLASSIFIER_ARCHITECTURES",
    "build_native_classifier_eval_transform",
    "build_native_classifier_model",
    "export_native_classifier_to_onnx",
    "find_classifier_metadata_json",
    "load_classifier_metadata_json",
    "normalize_classifier_augmentation_preset",
    "normalize_native_classifier_architecture",
    "resolve_auto_classifier_optimizer",
    "resolve_native_classifier_device",
    "resolve_native_classifier_model_path",
    "resolve_native_classifier_training_options",
    "summarize_classifier_imagefolder_root",
    "train_native_classifier",
]
